from .WillowsDad.WDWoodcutting import OSRSWDWoodcutting
from .WillowsDad.WDGlassblowing import OSRSWDGlassblowing
from .WillowsDad.WDFishing import OSRSWDFishing
from .WillowsDad.WillowsDad_bot import WillowsDadBot
from .WillowsDad.WDMining import OSRSWDMining
from .WillowsDad.WDMiningSand import OSRSWSand
from .hunterbotscript import OSRSHunter
from .cooking import OSRSCook
from .Cannonballs import Smithing
from .Bow_Fletcher.BowFletcher import OSRSBowFletcher
from .altar import OSRSAltar
from .BlastFurnace.BlastFurnace import OSRSBlastFurnace