from .WillowsDad.WDCombat import OSRSWDCombat
from .WillowsDad.WDWoodcutting import OSRSWDWoodcutting
from .WillowsDad.WDUltraCompost import OSRSWDUltraCompostMaker
from .WillowsDad.WDDegrimer import OSRSWDDegrimer
from .WillowsDad.WDFishing import OSRSWDFishing
from .WillowsDad.WillowsDad_bot import WillowsDadBot
from .WillowsDad.WDMining import OSRSWDMining
from .hunterbotscript import OSRSHunter
from .WillowsDad.WDThieving import OSRSWDThieving
from .WillowsDad.WDSmithing import OSRSWDSmithing
from .molchbot import OSRSMolch
from .cooking import OSRSCook
from .pickpocketer import OSRSPickpocket
from .nmz import OSRSNMZ
from .Cannonballs import Smithing
from .Bow_Fletcher.BowFletcher import OSRSBowFletcher